[package]
name = "spacekernel"
version = "0.1.0"
edition = "2024"

[features]
boot-self-test = []

[dependencies]
limine = { version = "=0.6.5", default-features = false }
font8x8 = { version = "=0.3.1", default-features = false, features = ["unicode"] }

[target.'cfg(target_arch = "x86_64")'.dependencies]
x86_64 = { version = "=0.15.4", default-features = false, features = ["instructions", "abi_x86_interrupt"] }

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
lto = true
codegen-units = 1
