#
#       rust-toolchain.toml
#       Reproducible Rust toolchain selection
#
#       2026/9/30 By JiTianYu391
#       Copyright (C) 2026 ViudiraTech.
#

[toolchain]
channel = "nightly-2026-05-24"
components = ["rustfmt"]
